from distutils.core import setup

setup(
    name='awsConfig',
    version='0.1',
    packages=['env.lib.python2.7.distutils', 'env.lib.python2.7.encodings', 'env.lib.python2.7.site-packages.pip',
              'env.lib.python2.7.site-packages.pip.req', 'env.lib.python2.7.site-packages.pip.vcs',
              'env.lib.python2.7.site-packages.pip.utils', 'env.lib.python2.7.site-packages.pip.compat',
              'env.lib.python2.7.site-packages.pip.models', 'env.lib.python2.7.site-packages.pip._vendor',
              'env.lib.python2.7.site-packages.pip._vendor.distlib',
              'env.lib.python2.7.site-packages.pip._vendor.distlib._backport',
              'env.lib.python2.7.site-packages.pip._vendor.colorama',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.trie',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.filters',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.serializer',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treewalkers',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treeadapters',
              'env.lib.python2.7.site-packages.pip._vendor.html5lib.treebuilders',
              'env.lib.python2.7.site-packages.pip._vendor.lockfile',
              'env.lib.python2.7.site-packages.pip._vendor.progress',
              'env.lib.python2.7.site-packages.pip._vendor.requests',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.chardet',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.util',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.contrib',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages',
              'env.lib.python2.7.site-packages.pip._vendor.requests.packages.urllib3.packages.ssl_match_hostname',
              'env.lib.python2.7.site-packages.pip._vendor.packaging',
              'env.lib.python2.7.site-packages.pip._vendor._markerlib',
              'env.lib.python2.7.site-packages.pip._vendor.cachecontrol',
              'env.lib.python2.7.site-packages.pip._vendor.cachecontrol.caches',
              'env.lib.python2.7.site-packages.pip._vendor.pkg_resources',
              'env.lib.python2.7.site-packages.pip.commands', 'env.lib.python2.7.site-packages.pip.operations',
              'env.lib.python2.7.site-packages.wheel', 'env.lib.python2.7.site-packages.wheel.test',
              'env.lib.python2.7.site-packages.wheel.test.simple.dist.simpledist',
              'env.lib.python2.7.site-packages.wheel.test.complex-dist.complexdist',
              'env.lib.python2.7.site-packages.wheel.tool', 'env.lib.python2.7.site-packages.wheel.signatures',
              'env.lib.python2.7.site-packages._markerlib', 'env.lib.python2.7.site-packages.setuptools',
              'env.lib.python2.7.site-packages.setuptools.command', 'env.lib.python2.7.site-packages.pkg_resources',
              'env.lib.python2.7.site-packages.pkg_resources._vendor',
              'env.lib.python2.7.site-packages.pkg_resources._vendor.packaging'],
    url='',
    license='',
    author='Filippo Gaudenzi',
    author_email='filippo.gaudenzi@unimi.it',
    description='awsReader4MoonCloud',
)
